config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "accounts#index"
  # devise_for :users

  resources :accounts do
    member do
      get 'check_mail'
    end
  end

  resources :mail_contents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  before_save :validate_data_before_save
  after_create :check_mail

  def self.reassign_heroku_app_name
    accounts = Account.where(error: nil)
    heroku_app_names = HerokuApp.where(shared_ip: nil).order(:id).limit(accounts.count).pluck(:name)
    accounts.each_with_index {|acc,i| acc.update(heroku_app_name: heroku_app_names[i])}
  end

  def check_mail keys="UNSEEN"
    url = "http://#{self.heroku_app_name}.herokuapp.com/imap?email=#{self.email}&password=#{self.password}&address=#{self.imap_address}&keys=#{keys}"
    r = RestClient.get url
    res = JSON.parse(r.body).with_indifferent_access
    if res[:results]
      res[:results].each do |r|
        if MailContent.find_by(message_id: r[:message_id]).nil?
          MailContent.create(r.merge(account_id: self.id))
        end
      end
      self.update(last_checked_at: Time.now) if !res[:results].empty?
    end

    if res[:error]
      self.update(last_checked_at: Time.now, error: res[:error])
    end
  end

  def imap_address
    return "outlook.office365.com" if !self.email.index("@hotmail.").nil? || !self.email.index("@outlook.").nil?
    return "imap.gmx.com" if !self.email.index("@gmx.com").nil?
  end

  private

  def validate_data_before_save
    if self.heroku_app_name.nil?
      heroku_app_names = Account.where.not(heroku_app_name: nil).pluck(:heroku_app_name)
      if heroku_app = HerokuApp.where(shared_ip: nil).where.not(name: heroku_app_names).first
        self.heroku_app_name = heroku_app.name
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/etsy_uploader_record.rb
class EtsyUploaderRecord < ActiveRecord::Base
  self.abstract_class = true

  establish_connection({
    "adapter"=> "postgresql",
    "encoding"=> "unicode",
    "gssencmode" => "disable",
    "url" => ENV["NINEID_DATABASE_URL"] || "postgres://postgres:Trangbeo1@masscrawler-db.quangpham.com:5432/etsy-uploader"
  })

end

app/models/heroku_app.rb
class HerokuApp < EtsyUploaderRecord
end

app/models/mail_content.rb
class MailContent < ApplicationRecord
  paginates_per 200
  # max_paginates_per 200
end

app/models/pubid_record.rb
class PubidRecord < ActiveRecord::Base
  self.abstract_class = true

  establish_connection({
    "adapter"=> "postgresql",
    "encoding"=> "unicode",
    "url" => ENV["NINEID_DATABASE_URL"] || "postgres://fqtrkvegusnpxs:f53c986150f90ae28ec3400379e5ebfcc646f392eb14ed2cae0fd2c1c5fd8eed@ec2-54-75-235-28.eu-west-1.compute.amazonaws.com:5432/debi3b41f3otv1"
  })

end

app/models/user.rb
class User < PubidRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: [:show, :edit, :update, :destroy, :check_mail]

  def index
    @accounts = Account.where(error: nil).where.not(last_checked_at: nil).order(:error).order(:id)
  end

  def show
    @mails = MailContent.where(account_id: @account.id).order(created_at: :desc).limit(100)
  end

  def new
    @account = Account.new
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @account.save
    redirect_to @account, notice: 'Account was successfully created.'
  end

  def update
    @account.update(account_params)
    redirect_to @account, notice: 'Account was successfully updated.'
  end

  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  def check_mail

  end

  private
  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:email, :password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected
  def authenticate_user!
    if user_signed_in?
      if current_user.apps.include?(request.host) || request.host == "localhost"
        super
      else
        ## if you want render 404 page
        # return render json: {host: request.host}
        render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
      end
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/mail_contents_controller.rb
class MailContentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @mails = MailContent.order(created_at: :desc).page params[:page]
  end
  def show
    @mail = MailContent.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<%= render "shared/menu"%>

<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<%= render "shared/menu"%>

<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table class="tiny-table" style="width: 100%;">
  <thead>
    <tr>
      <th>Id</th>
      <th>User name</th>
      <th>Last check</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.id %></td>
        <td><%= account.email %> <%= account.unread_count.to_i > 0 ? "(#{account.unread_count.to_i} unread)" : "" %></td>
        <td><%= account.last_checked_at %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<%= render "shared/menu"%>

<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<%= render "shared/menu"%>

<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<table class="tiny-table" style="width: 100%;">
  <thead>
    <tr>
      <th>Created</th>
      <th>From</th>
      <th>Subject</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @mails.each do |mail| %>
      <tr>
        <td><%= mail.created_at %></td>
        <td><%= mail.from %></td>
        <td><%= mail.subject %></td>
        <td><%= link_to 'Show', mail %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IMAPChecker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mail_contents/index.html.erb
<%= render "shared/menu"%>

<table class="tiny-table" style="width: 100%;">
  <thead>
    <tr>
      <th>Created</th>
      <th>To</th>
      <th>From</th>
      <th>Subject</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @mails.each do |mail| %>
      <tr>
        <td><%= mail.created_at %></td>
        <td><%= mail.to %></td>
        <td><%= mail.from %></td>
        <td><%= mail.subject %></td>
        <td><%= link_to 'Show', mail %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @mails %>

app/views/mail_contents/show.html.erb
<%= render "shared/menu"%>

<%= @mail.html_part.nil? ? "" : @mail.html_part.html_safe %>
<br><br>
<% if !@mail.text_part.nil?  %>
  <% @mail.text_part.split("\n") do |p| %>
    <%= p %><br>
  <% end %>
<% end %>

app/views/shared/_menu.html.erb
<table class="tiny-table" style="width: 100%;">
  <tbody>
    <tr>
      <td>
        Menu:

        <% if user_signed_in? %>
          <%= link_to 'Accounts', accounts_path %>
          <%= link_to 'All mails', mail_contents_path %>
        <% end %>
      </td>
      <td style="text-align: right;">
        <% if user_signed_in? %>
          <%= current_user.name || current_user.email %><br>
          <%#= link_to "Change your password", edit_user_registration_path %>
          <%#= link_to "Change password", settings_change_password_path %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        <% end %>
      </td>
    </tr>

  </tbody>
</table>